import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// Complete polling station data: 199 entries with A/B splits
const POLLING_STATIONS_DATA: [string, string, string][] = [
  // OSABENE MILE 50 (9)
  ['E050101A', 'MILE 50 M. A. PRIMARY 1', 'OSABENE MILE 50'],
  ['E050101B', 'MILE 50 M. A. PRIMARY 1', 'OSABENE MILE 50'],
  ['E050102A', 'MILE 50 M. A. PRIMARY 2', 'OSABENE MILE 50'],
  ['E050102B', 'MILE 50 M. A. PRIMARY 2', 'OSABENE MILE 50'],
  ['E050103', 'MILE 50 M. A. JHS', 'OSABENE MILE 50'],
  ['E050104A', 'CHRIST CHAPEL PRESBY', 'OSABENE MILE 50'],
  ['E050104B', 'CHRIST CHAPEL PRESBY', 'OSABENE MILE 50'],
  ['E050105', 'DAY SPRING INT. SCH 1', 'OSABENE MILE 50'],
  ['E050106', 'DAY SPRING INT. SCH 2', 'OSABENE MILE 50'],
  // ADWESO ESTATE (5)
  ['E050201', 'HOUSING CORPORATION OFFICE ADWESO', 'ADWESO ESTATE'],
  ['E050202', 'ST DOMINIC PRIMARY SCHOOL ADWESO 1', 'ADWESO ESTATE'],
  ['E050203', 'ST DOMINIC PRIMARY SCHOOL ADWESO 2', 'ADWESO ESTATE'],
  ['E050204', 'WESLEY INTERNATIONAL SCH. 1', 'ADWESO ESTATE'],
  ['E050205', 'WESLEY INTERNATIONAL SCH. 2', 'ADWESO ESTATE'],
  // ADWESO TOWN (10)
  ['E050301', 'GOOD NEWS PREP. SCH. ADWESO 1', 'ADWESO TOWN'],
  ['E050302', 'GOOD NEWS PREP. SCH. ADWESO 2', 'ADWESO TOWN'],
  ['E050303', 'PRESBY CHURCH AGBOGRI 1', 'ADWESO TOWN'],
  ['E050304', 'PRESBY CHURCH AGBOGRI 2', 'ADWESO TOWN'],
  ['E050305A', 'MOSES COM. SCH. ADWESO', 'ADWESO TOWN'],
  ['E050305B', 'MOSES COM. SCH. ADWESO', 'ADWESO TOWN'],
  ['E050306', 'BETHEL PRESBY ADWESO 1', 'ADWESO TOWN'],
  ['E050307', 'BETHEL PRESBY ADWESO 2', 'ADWESO TOWN'],
  ['E050308A', 'CENTRAL ACADEMY ADWESO', 'ADWESO TOWN'],
  ['E050308B', 'CENTRAL ACADEMY ADWESO', 'ADWESO TOWN'],
  // TWO STREAMS (8)
  ['E050401A', 'METHODIST CHAPEL', 'TWO STREAMS'],
  ['E050401B', 'METHODIST CHAPEL', 'TWO STREAMS'],
  ['E050402', 'NURSES TRAINING SCHOOL 1', 'TWO STREAMS'],
  ['E050403A', 'NURSES TRAINING SCHOOL 2', 'TWO STREAMS'],
  ['E050403B', 'NURSES TRAINING SCHOOL 2', 'TWO STREAMS'],
  ['E050404', 'PENTECOST CHURCH  TWO STREAMS 1', 'TWO STREAMS'],
  ['E050405', 'PENTECOST CHURCH  TWO STREAMS 2', 'TWO STREAMS'],
  ['E050406', 'PENTECOST CHURCH  TWO STREAMS 3', 'TWO STREAMS'],
  // NYEREDE NORTH (9)
  ['E050501A', 'ANGLICAN PRI. SCH.KORLE NKWANTA 1', 'NYEREDE NORTH'],
  ['E050501B', 'ANGLICAN PRI. SCH.KORLE NKWANTA 1', 'NYEREDE NORTH'],
  ['E050502', 'ANGLICAN PRI. SCH.KORLE NKWANTA 2', 'NYEREDE NORTH'],
  ['E050503', 'BETHEL METH. CHU.KORLE NKWANTA 1', 'NYEREDE NORTH'],
  ['E050504', 'BETHEL METH. CHU.KORLE NKWANTA 2', 'NYEREDE NORTH'],
  ['E050505', 'R.C. PRIM. SCH. AGAVENYA 1', 'NYEREDE NORTH'],
  ['E050506', 'R.C. PRIM. SCH. AGAVENYA 2', 'NYEREDE NORTH'],
  ['E050507A', 'METHODIST CHURCH OKPER', 'NYEREDE NORTH'],
  ['E050507B', 'METHODIST CHURCH OKPER', 'NYEREDE NORTH'],
  // NYEREDE SOUTH (7)
  ['E050601A', 'PRESBY PRIM. SCH. BONYA 1', 'NYEREDE SOUTH'],
  ['E050601B', 'PRESBY PRIM. SCH. BONYA 1', 'NYEREDE SOUTH'],
  ['E050602', 'PRESBY PRIM. SCH. BONYA 2', 'NYEREDE SOUTH'],
  ['E050603A', 'M.A JHS. SCH. TROM 1', 'NYEREDE SOUTH'],
  ['E050603B', 'M.A JHS. SCH. TROM 1', 'NYEREDE SOUTH'],
  ['E050604A', 'M.A JHS. SCH. TROM 2', 'NYEREDE SOUTH'],
  ['E050604B', 'M.A JHS. SCH. TROM 2', 'NYEREDE SOUTH'],
  // RESDENTIAL AREA (9)
  ['E050701', 'POLICE CANTEEN GALLOWAY', 'RESDENTIAL AREA'],
  ['E050702', 'SEC/TEC. SCH. LIBRARY', 'RESDENTIAL AREA'],
  ['E050703', 'SEC/TEC. SCH. PAVILLION', 'RESDENTIAL AREA'],
  ['E050704', 'SEC/TEC. ADMINISTRATION', 'RESDENTIAL AREA'],
  ['E050705A', 'ATEKYEM 1', 'RESDENTIAL AREA'],
  ['E050705B', 'ATEKYEM 1', 'RESDENTIAL AREA'],
  ['E050706A', 'ATEKYEM 2', 'RESDENTIAL AREA'],
  ['E050706B', 'ATEKYEM 2', 'RESDENTIAL AREA'],
  ['E050707', 'MINISTERIES CANTEEN KOFORIDUA', 'RESDENTIAL AREA'],
  // OGUAA (5)
  ['E050801A', 'LEGION HALL', 'OGUAA'],
  ['E050801B', 'LEGION HALL', 'OGUAA'],
  ['E050802', 'FORESTRY DEPT. OFFICE', 'OGUAA'],
  ['E050803A', "PRESBY A PRIM SCH K'DUA", 'OGUAA'],
  ['E050803B', "PRESBY A PRIM SCH K'DUA", 'OGUAA'],
  // ASUOFIRISO (1)
  ['E050901', "PRESBY 'B' JHS KOFORIDUA", 'ASUOFIRISO'],
  // ANGLICAN (3)
  ['E051001', "ST. PETER'S JHS K'DUA", 'ANGLICAN'],
  ['E051002', "ST. PETER'S PRIMARY K'DUA", 'ANGLICAN'],
  ['E051003', "ST. MARY'S KINDARGATEN K'DUA", 'ANGLICAN'],
  // ADONTUA (4)
  ['E051101', 'APOSTOLIC CHURCH OF GHANA 1', 'ADONTUA'],
  ['E051102', 'APOSTOLIC CHURCH OF GHANA 2', 'ADONTUA'],
  ['E051103', 'ADONTUA NORTH 1', 'ADONTUA'],
  ['E051104', 'ADONTUA NORTH 2', 'ADONTUA'],
  // OHEMAA PARK (2)
  ['E051201', 'OHEMAA PARK', 'OHEMAA PARK'],
  ['E051202', 'ABOTANSO', 'OHEMAA PARK'],
  // SCHOOL TOWN (4)
  ['E051301A', 'METHODIST PRIM SCHOOL', 'SCHOOL TOWN'],
  ['E051301B', 'METHODIST PRIM SCHOOL', 'SCHOOL TOWN'],
  ['E051302', "METHODIST C&D SCHOOL K'DUA 1", 'SCHOOL TOWN'],
  ['E051303', "METHODIST C&D SCHOOL K'DUA 2", 'SCHOOL TOWN'],
  // OLD ESTATE WEST (10)
  ['E051401', "VETINARY DEPT OFFICE K'DUA 1", 'OLD ESTATE WEST'],
  ['E051402', "VETINARY DEPT OFFICE K'DUA 2", 'OLD ESTATE WEST'],
  ['E051403', 'DAASEBRE POLLING STATION', 'OLD ESTATE WEST'],
  ['E051404A', 'VOTER HOUSE POLLING STATION', 'OLD ESTATE WEST'],
  ['E051404B', 'VOTER HOUSE POLLING STATION', 'OLD ESTATE WEST'],
  ['E051405', 'DENSUANO POLLING STATION 1', 'OLD ESTATE WEST'],
  ['E051406', 'DENSUANO POLLING STATION 2', 'OLD ESTATE WEST'],
  ['E051407', 'SSNIT FLAT POLLING STATION 1', 'OLD ESTATE WEST'],
  ['E051408', 'SSNIT FLAT POLLING STATION 2', 'OLD ESTATE WEST'],
  ['E051409', 'NYAMETEASE EP SCHOOL', 'OLD ESTATE WEST'],
  // OLD ESTATE EAST (3)
  ['E051501', 'HOUSING CORP OFFICE OLD ESTATE 1', 'OLD ESTATE EAST'],
  ['E051502', 'HOUSING CORP OFFICE OLD ESTATE 2', 'OLD ESTATE EAST'],
  ['E051503', 'PENTECOST PREPARATORY SCHOOL', 'OLD ESTATE EAST'],
  // TANOSO (4)
  ['E051601', 'TANOSO SOUTH 1', 'TANOSO'],
  ['E051602', 'TANOSO SOUTH 2', 'TANOSO'],
  ['E051603', 'TANOSO CENTRAL', 'TANOSO'],
  ['E051604', 'TANOSO NORTH', 'TANOSO'],
  // NSUKWAOSO ABOTANSO (7)
  ['E051701', "ST. ANNE'S JHS KOFORIDUA", 'NSUKWAOSO ABOTANSO'],
  ['E051702', "ST. ANNE'S KINDARGATEN 1", 'NSUKWAOSO ABOTANSO'],
  ['E051703', "ST. ANNE'S KINDARGATEN 2", 'NSUKWAOSO ABOTANSO'],
  ['E051704', 'ANGLICAN PRIMARY', 'NSUKWAOSO ABOTANSO'],
  ['E051705', 'SARKODIE JHS KOFORIDUA 1', 'NSUKWAOSO ABOTANSO'],
  ['E051706', 'SARKODIE JHS KOFORIDUA 2', 'NSUKWAOSO ABOTANSO'],
  ['E051707', "SARKODIE PRIMARY SCH. K'DUA", 'NSUKWAOSO ABOTANSO'],
  // NSUKWAOSO (6)
  ['E051801', 'S.D.A EDUCATION UNIT', 'NSUKWAOSO'],
  ['E051802', 'APAACHE', 'NSUKWAOSO'],
  ['E051803', 'MALLAM PARK 1', 'NSUKWAOSO'],
  ['E051804', 'MALLAM PARK 2', 'NSUKWAOSO'],
  ['E051805', 'METHODIST EDUCATION UNIT', 'NSUKWAOSO'],
  ['E051806', 'TIMBER MARKET', 'NSUKWAOSO'],
  // RAILWAY STATION (3)
  ['E051901', 'RAILWAY STATION 1', 'RAILWAY STATION'],
  ['E051902', 'RAILWAY STATION 2', 'RAILWAY STATION'],
  ['E051903', 'FIRE SERVICE STATION', 'RAILWAY STATION'],
  // DEBRAKROM (3)
  ['E052001', 'METHODIST BOYS SCH. KOFORIDUA 1', 'DEBRAKROM'],
  ['E052002', 'METHODIST BOYS SCH. KOFORIDUA 2', 'DEBRAKROM'],
  ['E052003', 'APPENTENG HALL', 'DEBRAKROM'],
  // AKWAASU ASEBI (7)
  ['E052101', 'EVA MARIA JHS KOFORIDUA', 'AKWAASU ASEBI'],
  ['E052102', 'RC UPPER PRIM SCH. 1', 'AKWAASU ASEBI'],
  ['E052103', 'RC UPPER PRIM SCH. 2', 'AKWAASU ASEBI'],
  ['E052104', 'KOFORIDUAMU POLLING STATION', 'AKWAASU ASEBI'],
  ['E052105A', 'PAMPAMAHENE', 'AKWAASU ASEBI'],
  ['E052105B', 'PAMPAMAHENE', 'AKWAASU ASEBI'],
  ['E052106', 'CENTRAL POLICE STATION', 'AKWAASU ASEBI'],
  // CENTRAL MARKET AREA (5)
  ['E052201A', 'KWAKU OCTERE DEPOT 1', 'CENTRAL MARKET AREA'],
  ['E052201B', 'KWAKU OCTERE DEPOT 1', 'CENTRAL MARKET AREA'],
  ['E052202', 'KWAKU OCTERE DEPOT 2', 'CENTRAL MARKET AREA'],
  ['E052203A', 'MCH CLINIC KOFORIDUA', 'CENTRAL MARKET AREA'],
  ['E052203B', 'MCH CLINIC KOFORIDUA', 'CENTRAL MARKET AREA'],
  // SOCIAL WELFARE (6)
  ['E052301A', 'FISHING CORPORATION', 'SOCIAL WELFARE'],
  ['E052301B', 'FISHING CORPORATION', 'SOCIAL WELFARE'],
  ['E052302', 'SOCIAL WELFARE OFFICE KOFORIDUA 1', 'SOCIAL WELFARE'],
  ['E052303A', 'SOCIAL WELFARE OFFICE KOFORIDUA 2', 'SOCIAL WELFARE'],
  ['E052303B', 'SOCIAL WELFARE OFFICE KOFORIDUA 2', 'SOCIAL WELFARE'],
  ['E052304', 'GLAMOUR POLLING STATION', 'SOCIAL WELFARE'],
  // KANTUDU (5)
  ['E052401', "A M E ZION PRIM. SCH. K'DUA", 'KANTUDU'],
  ['E052402', "KANTUDU NORTH K'DUA", 'KANTUDU'],
  ['E052403', "SCC OFFICE K'DUA 1", 'KANTUDU'],
  ['E052404', "SCC OFFICE K'DUA 2", 'KANTUDU'],
  ['E052405', 'WATER AND SEWERAGE OFFICE K\'DUA', 'KANTUDU'],
  // CENTRAL HOSPITAL (4)
  ['E052501', 'E.P CHURCH', 'CENTRAL HOSPITAL'],
  ['E052502A', "CENTRAL HOSPITAL O.P.D K'DUA 1", 'CENTRAL HOSPITAL'],
  ['E052502B', "CENTRAL HOSPITAL O.P.D K'DUA 1", 'CENTRAL HOSPITAL'],
  ['E052503', "CENTRAL HOSPITAL O.P.D K'DUA 2", 'CENTRAL HOSPITAL'],
  // ANLO TOWN SOUTH (6)
  ['E052601', 'ANLO TOWN SOUTH 1', 'ANLO TOWN SOUTH'],
  ['E052602', 'ANLO TOWN SOUTH 2', 'ANLO TOWN SOUTH'],
  ['E052603', "ANLO TOWN SOUTH 'B' 1", 'ANLO TOWN SOUTH'],
  ['E052604', "ANLO TOWN SOUTH 'B' 2", 'ANLO TOWN SOUTH'],
  ['E052605', 'ANLO TOWN DOWN SOUTH 1', 'ANLO TOWN SOUTH'],
  ['E052606', 'ANLO TOWN DOWN SOUTH 2', 'ANLO TOWN SOUTH'],
  // ANLO TOWN NORTH (3)
  ['E052701', "A M E ZION J H S K'DUA", 'ANLO TOWN NORTH'],
  ['E052702', "BETHEL PENTECOST CHURCH K'DUA 1", 'ANLO TOWN NORTH'],
  ['E052703', "BETHEL PENTECOST CHURCH K'DUA 2", 'ANLO TOWN NORTH'],
  // KLU TOWN (5)
  ['E052801', 'APEMPOA SCHOOL KOFORIDUA 1', 'KLU TOWN'],
  ['E052802', 'APEMPOA SCHOOL KOFORIDUA 2', 'KLU TOWN'],
  ['E052803', "RAILWAY POLICE QUARTERS K'DUA 1", 'KLU TOWN'],
  ['E052804', "RAILWAY POLICE QUARTERS K'DUA 2", 'KLU TOWN'],
  ['E052805', 'KLU TOWN', 'KLU TOWN'],
  // COMMUNITY A & B (6)
  ['E052901', 'CHIEF DAGOMBA MOSQUE', 'COMMUNITY A & B'],
  ['E052902A', 'HAUSA MOSQUE', 'COMMUNITY A & B'],
  ['E052902B', 'HAUSA MOSQUE', 'COMMUNITY A & B'],
  ['E052903', 'KEKERE POLLING STATION', 'COMMUNITY A & B'],
  ['E052904', 'MAHD - DEEN ISLAMIC J H S N/TOWN 1', 'COMMUNITY A & B'],
  ['E052905', 'MAHD - DEEN ISLAMIC J H S N/TOWN 2', 'COMMUNITY A & B'],
  // COMMUNITY C (7)
  ['E053001', 'HAJIA BABY 1', 'COMMUNITY C'],
  ['E053002', 'HAJIA BABY 2', 'COMMUNITY C'],
  ['E053003', 'MAIKANO POLLING STATION', 'COMMUNITY C'],
  ['E053004', 'MADINA MOSQUE', 'COMMUNITY C'],
  ['E053005', 'TASALA MOSQUE', 'COMMUNITY C'],
  ['E053006', 'ZONGO CLINIC 1', 'COMMUNITY C'],
  ['E053007', 'ZONGO CLINIC 2', 'COMMUNITY C'],
  // COMMUNITY D (7)
  ['E053101', 'CHIEF BUTCHER 1', 'COMMUNITY D'],
  ['E053102', 'CHIEF BUTCHER 2', 'COMMUNITY D'],
  ['E053103', 'CHIEF BUTCHER 3', 'COMMUNITY D'],
  ['E053104', 'L / A PRIM. SCH. OKOMESO', 'COMMUNITY D'],
  ['E053105', 'JUDAH PREP. SCH.', 'COMMUNITY D'],
  ['E053106A', 'KROBO JUNCTION MOSQUE', 'COMMUNITY D'],
  ['E053106B', 'KROBO JUNCTION MOSQUE', 'COMMUNITY D'],
  // ADA (11)
  ['E053201A', 'KOFORIDUA SENIOR HIGH SCH. 1', 'ADA'],
  ['E053201B', 'KOFORIDUA SENIOR HIGH SCH. 1', 'ADA'],
  ['E053202', 'KOFORIDUA SENIOR HIGH SCH. 2', 'ADA'],
  ['E053203', 'KOFORIDUA SENIOR HIGH SCH. 3', 'ADA'],
  ['E053204', 'KOFORIDUA SENIOR HIGH SCH. 4', 'ADA'],
  ['E053205A', 'ADA MAGAZINE 1', 'ADA'],
  ['E053205B', 'ADA MAGAZINE 1', 'ADA'],
  ['E053206A', 'ADA MAGAZINE 2', 'ADA'],
  ['E053206B', 'ADA MAGAZINE 2', 'ADA'],
  ['E053207', 'L / A J H S ADA 1', 'ADA'],
  ['E053208', 'L / A J H S ADA 2', 'ADA'],
  // NYAMEKROM (4)
  ['E053301', 'R C PRIM. SCH. NYAMEKROM 1', 'NYAMEKROM'],
  ['E053302A', 'R C PRIM. SCH. NYAMEKROM 2', 'NYAMEKROM'],
  ['E053302B', 'R C PRIM. SCH. NYAMEKROM 2', 'NYAMEKROM'],
  ['E053303', 'KWAME DJANKROM', 'NYAMEKROM'],
  // SEMPOAMIENSA (11)
  ['E053401A', 'KOFORIDUA POLY POLLING STATION 1', 'SEMPOAMIENSA'],
  ['E053401B', 'KOFORIDUA POLY POLLING STATION 1', 'SEMPOAMIENSA'],
  ['E053402A', 'KOFORIDUA POLY POLLING STATION 2', 'SEMPOAMIENSA'],
  ['E053402B', 'KOFORIDUA POLY POLLING STATION 2', 'SEMPOAMIENSA'],
  ['E053403A', 'KOFORIDUA POLY POLLING STATION 3', 'SEMPOAMIENSA'],
  ['E053403B', 'KOFORIDUA POLY POLLING STATION 3', 'SEMPOAMIENSA'],
  ['E053404', 'SEMPOAMIENSA JUNCTION', 'SEMPOAMIENSA'],
  ['E053405', 'SEMPOAMIENSA M / A BASIC SCH.', 'SEMPOAMIENSA'],
  ['E053406A', 'APENKWA PENTECOST', 'SEMPOAMIENSA'],
  ['E053406B', 'APENKWA PENTECOST', 'SEMPOAMIENSA'],
  ['E053407', 'MONROVIA CHURCH OF PENTECOST', 'SEMPOAMIENSA'],
];

async function main() {
  console.log('ðŸŒ± Starting database seed...');
  console.log(`ðŸ“Š Total polling stations to seed: ${POLLING_STATIONS_DATA.length}`);

  // Group polling stations by electoral area
  const areaMap = new Map<string, { code: string; stations: { code: string; name: string }[] }>();

  for (const [psCode, psName, areaName] of POLLING_STATIONS_DATA) {
    const areaCode = areaName.toUpperCase().replace(/\s+/g, '-').replace(/&/g, 'AND');
    
    if (!areaMap.has(areaName)) {
      areaMap.set(areaName, { code: areaCode, stations: [] });
    }
    
    areaMap.get(areaName)!.stations.push({ code: psCode, name: psName });
  }

  // Create electoral areas and polling stations
  for (const [areaName, data] of Array.from(areaMap.entries())) {
    const { code, stations } = data;
    const area = await prisma.electoralArea.upsert({
      where: { code },
      update: {},
      create: {
        name: areaName,
        code,
      },
    });

    for (const station of stations) {
      await prisma.pollingStation.upsert({
        where: { code: station.code },
        update: {},
        create: {
          name: station.name,
          code: station.code,
          electoralAreaId: area.id,
        },
      });
    }
  }

  // Create default admin user
  const hashedPassword = await bcrypt.hash('admin123', 10);
  await prisma.user.upsert({
    where: { email: 'admin' },
    update: {},
    create: {
      name: 'Admin User',
      email: 'admin',
      passwordHash: hashedPassword,
      role: 'ADMIN',
    },
  });

  // Create super admin recovery account
  const superAdminPassword = await bcrypt.hash('superadmin123', 10);
  await prisma.user.upsert({
    where: { email: 'superadmin' },
    update: {
      role: 'SUPER_ADMIN',
      isActive: true,
    },
    create: {
      name: 'Super Admin',
      email: 'superadmin',
      passwordHash: superAdminPassword,
      role: 'SUPER_ADMIN',
      isActive: true,
    },
  });

  const areaCount = await prisma.electoralArea.count();
  const stationCount = await prisma.pollingStation.count();
  const userCount = await prisma.user.count();

  console.log('âœ… Seed completed successfully!');
  console.log(`   - ${areaCount} electoral areas created`);
  console.log(`   - ${stationCount} polling stations created`);
  console.log(`   - ${userCount} users available (admin: admin/admin123, superadmin: superadmin/superadmin123)`);
}

main()
  .catch((e) => {
    console.error('âŒ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });


